language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database homepage_test;' -U postgres
  - bundle exec rake db:migrate
  - cp config/application.yml.template config/application.yml
script: bundle exec rspec spec
