language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
before_script:
  - cp config/database.example.yml config/database.yml
  - mysql -e 'create database homepage_test;'
  - bundle exec rake db:migrate
  - cp config/application.yml.template config/application.yml
script: bundle exec rspec spec