development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: homepage_development
  pool: 5
  user: postgres
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: homepage_test
  pool: 5
  user: postgres
  password:
